=== Hl4p3x/L2JHELLAS/L2JHellasD/data/xml/spawn/spawn.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT list (spawn|location)*>
<!ELEMENT spawn (territory|npc)*>
<!ATTLIST spawn
        spawn_bydefault CDATA #REQUIRED
        name CDATA #REQUIRED
        event_name CDATA #IMPLIED>
<!ELEMENT territory (location)*>
<!ELEMENT location (#PCDATA)>
<!ATTLIST location
        maxz CDATA #REQUIRED
        minz CDATA #REQUIRED
        x CDATA #REQUIRED
        y CDATA #REQUIRED>
<!ELEMENT npc (ai_params)*>
<!ATTLIST npc
        count CDATA #REQUIRED
        id CDATA #REQUIRED
        respawn CDATA #IMPLIED
        respawn_rand CDATA #IMPLIED
        pos CDATA #IMPLIED>
<!ELEMENT ai_params (set)*>
<!ELEMENT set (#PCDATA)>
<!ATTLIST set
        name CDATA #REQUIRED
        val CDATA #REQUIRED>

=== Hl4p3x/L2JHELLAS/L2JHellasD/data/xml/spawn/21_20.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE list SYSTEM "spawn.dtd">
<list>
	<spawn spawn_bydefault="true"  name="[oren01_qm2019_05]">
		<territory>	
			<location x="40444" y="68984" minz="-3548" maxz="-3148" />
			<location x="43596" y="68888" minz="-3548" maxz="-3148" />
			<location x="44672" y="69892" minz="-3548" maxz="-3148" />
			<location x="44072" y="71904" minz="-3548" maxz="-3148" />
			<location x="41112" y="70332" minz="-3548" maxz="-3148" />
		</territory>
		<npc id="27064" count="1" respawn="180" />	
	</spawn>
	<spawn spawn_bydefault="true"  name="[oren01_qm2019_06]">
		<territory>	
			<location x="33004" y="78680" minz="-3748" maxz="-3298" />
			<location x="37372" y="79728" minz="-3748" maxz="-3298" />
			<location x="38244" y="83040" minz="-3748" maxz="-3298" />
			<location x="33060" y="83048" minz="-3748" maxz="-3298" />
		</territory>
		<npc id="27065" count="1" respawn="180" />	
	</spawn>
	<spawn spawn_bydefault="true"  name="[oren01_qm2019_07]">
		<territory>	
			<location x="46508" y="89244" minz="-3772" maxz="-3372" />
			<location x="48304" y="90876" minz="-3772" maxz="-3372" />
			<location x="47488" y="92304" minz="-3772" maxz="-3372" />
			<location x="45004" y="92160" minz="-3772" maxz="-3372" />
		</territory>
		<npc id="27067" count="1" respawn="180" />	
	</spawn>
	<spawn spawn_bydefault="true"  name="[oren01_qm2019_08]">
		<territory>	
			<location x="56804" y="77312" minz="-3656" maxz="-3356" />
			<location x="58504" y="76840" minz="-3656" maxz="-3356" />
			<location x="58780" y="80240" minz="-3656" maxz="-3356" />
			<location x="56760" y="80072" minz="-3656" maxz="-3356" />
			<location x="56016" y="78784" minz="-3656" maxz="-3356" />
		</territory>
		<npc id="27068" count="1" respawn="180" />	
	</spawn>
	<spawn spawn_bydefault="true"  name="[oren01_qm2120_07]">
		<territory>	
			<location x="55560" y="89836" minz="-3784" maxz="-3384" />
			<location x="57188" y="89220" minz="-3784" maxz="-3384" />
			<location x="57756" y="90292" minz="-3784" maxz="-3384" />
			<location x="57132" y="91152" minz="-3784" maxz="-3384" />
			<location x="55936" y="91236" minz="-3784" maxz="-3384" />
		</territory>
		<npc id="27077" count="1" respawn="180" />	
	</spawn>
	<spawn spawn_bydefault="true"  name="[oren01_qm2120_08]">
		<territory>	
			<location x="49012" y="90172" minz="-3748" maxz="-3348" />
			<location x="50100" y="90600" minz="-3748" maxz="-3348" />
			<location x="50080" y="91664" minz="-3748" maxz="-3348" />
			<location x="49068" y="92144" minz="-3748" maxz="-3348" />
			<location x="48224" y="91148" minz="-3748" maxz="-3348" />
		</territory>
		<npc id="27077" count="1" respawn="180" />	
	</spawn>
	<spawn spawn_bydefault="true"  name="[oren01_qm2120_09]">
		<territory>	
			<location x="42452" y="92644" minz="-3716" maxz="-3316" />
			<location x="43616" y="92100" minz="-3716" maxz="-3316" />
			<location x="44404" y="93556" minz="-3716" maxz="-3316" />
			<location x="43788" y="94300" minz="-3716" maxz="-3316" />
		</territory>
		<npc id="27077" count="1" respawn="180" />	
	</spawn>
	<spawn spawn_bydefault="true"  name="[oren01_qm2120_10]">
		<territory>	
			<location x="38128" y="90112" minz="-3528" maxz="-3128" />
			<location x="39000" y="90512" minz="-3528" maxz="-3128" />
			<location x="38036" y="91784" minz="-3528" maxz="-3128" />
			<location x="37308" y="91120" minz="-3528" maxz="-3128" />
		</territory>
		<npc id="27077" count="1" respawn="180" />	
	</spawn>
	<spawn spawn_bydefault="true"  name="[oren01_qm2120_11]">
		<territory>	
			<location x="34424" y="89224" minz="-3640" maxz="-3240" />
			<location x="35572" y="89364" minz="-3640" maxz="-3240" />
			<location x="35276" y="90860" minz="-3640" maxz="-3240" />
			<location x="34104" y="90288" minz="-3640" maxz="-3240" />
		</territory>
		<npc id="27077" count="1" respawn="180" />	
	</spawn>
	<spawn spawn_bydefault="true"  name="[oren01_qm2120_12]">
		<territory>	
			<location x="45656" y="89260" minz="-3676" maxz="-3276" />
			<location x="46760" y="88600" minz="-3676" maxz="-3276" />
			<location x="47960" y="89840" minz="-3676" maxz="-3276" />
			<location x="46040" y="90272" minz="-3676" maxz="-3276" />
		</territory>
		<npc id="27077" count="1" respawn="180" />	
	</spawn>
	<spawn spawn_bydefault="true"  name="[oren06_npc2120_001]">
		<npc id="30749" count="1" respawn="60" pos="63906 74711 -3700 57344" />	
	</spawn>
	<spawn spawn_bydefault="true"  name="[oren06_npc2120_002]">
		<npc id="30371" count="1" respawn="60" pos="51210 82474 -3283 6000" />	
	</spawn>
	<spawn spawn_bydefault="true"  name="[oren02_npc2120_g01]">
		<territory>	
			<location x="46968" y="67420" minz="-3830" maxz="-2830" />
			<location x="56293" y="71007" minz="-3830" maxz="-2830" />
			<location x="57197" y="74981" minz="-3830" maxz="-2830" />
			<location x="41712" y="67386" minz="-3830" maxz="-2830" />
		</territory>
		<npc id="31033" count="1" respawn="60" />	
	</spawn>
	<spawn spawn_bydefault="true"  name="[oren02_npc2120_g02]">
		<territory>	
			<location x="56883" y="78715" minz="-3830" maxz="-3130" />
			<location x="59196" y="79451" minz="-3830" maxz="-3130" />
			<location x="59556" y="92906" minz="-3830" maxz="-3130" />
			<location x="51064" y="92339" minz="-3830" maxz="-3130" />
		</territory>
		<npc id="31033" count="1" respawn="60" />	
	</spawn>
	<spawn spawn_bydefault="true"  name="[oren02_npc2120_g03]">
		<territory>	
			<location x="33123" y="82418" minz="-3857" maxz="-3157" />
			<location x="39324" y="83590" minz="-3857" maxz="-3157" />
			<location x="45351" y="92922" minz="-3857" maxz="-3157" />
			<location x="33334" y="90321" minz="-3857" maxz="-3157" />
		</territory>
		<npc id="31033" count="1" respawn="60" />	
	</spawn>
	<spawn spawn_bydefault="true"  name="[oren02_npc2120_g04]">
		<territory>	
			<location x="32976" y="67413" minz="-3778" maxz="-3078" />
			<location x="36579" y="67531" minz="-3778" maxz="-3078" />
			<location x="37720" y="82930" minz="-3778" maxz="-3078" />
			<location x="33259" y="81928" minz="-3778" maxz="-3078" />
		</territory>
		<npc id="31033" count="1" respawn="60" />	
	</spawn>

</list>

=== Hl4p3x/L2JHELLAS/L2JHellasD/data/xml/spawn/25_20.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE list SYSTEM "spawn.dtd">
<list>
	<spawn name="[aden10_2520_01]">
		<territory>	
			<location x="163964" y="65628" minz="-3784" maxz="-3584" />
			<location x="166260" y="65636" minz="-3784" maxz="-3584" />
			<location x="167916" y="66900" minz="-3784" maxz="-3584" />
			<location x="163984" y="66868" minz="-3784" maxz="-3584" />
		</territory>
		<npc id="20640" count="1" respawn="23" />	
		<npc id="20641" count="2" respawn="23" />	
		<npc id="20642" count="1" respawn="23" />	
	</spawn>
	<spawn name="[aden10_2520_02]">
		<territory>	
			<location x="163944" y="67316" minz="-3456" maxz="-3006" />
			<location x="166248" y="67240" minz="-3456" maxz="-3006" />
			<location x="167016" y="68020" minz="-3456" maxz="-3006" />
			<location x="166108" y="69692" minz="-3456" maxz="-3006" />
			<location x="163920" y="69628" minz="-3456" maxz="-3006" />
		</territory>
		<npc id="20640" count="1" respawn="23" />	
		<npc id="20641" count="2" respawn="23" />	
		<npc id="20642" count="1" respawn="23" />	
	</spawn>
	<spawn name="[aden10_2520_03]">
		<territory>	
			<location x="164036" y="69844" minz="-3172" maxz="-2822" />
			<location x="166152" y="70024" minz="-3172" maxz="-2822" />
			<location x="166604" y="72564" minz="-3172" maxz="-2822" />
			<location x="165796" y="73504" minz="-3172" maxz="-2822" />
			<location x="164032" y="73700" minz="-3172" maxz="-2822" />
		</territory>
		<npc id="20640" count="3" respawn="23" />	
		<npc id="20641" count="3" respawn="23" />	
		<npc id="20642" count="3" respawn="23" />	
	</spawn>
	<spawn name="[aden10_2520_04]">
		<territory>	
			<location x="164120" y="74116" minz="-3164" maxz="-2064" />
			<location x="165344" y="73908" minz="-3164" maxz="-2064" />
			<location x="166740" y="76632" minz="-3164" maxz="-2064" />
			<location x="166404" y="80164" minz="-3164" maxz="-2064" />
			<location x="163956" y="80052" minz="-3164" maxz="-2064" />
		</territory>
		<npc id="20643" count="2" respawn="23" />	
		<npc id="20644" count="3" respawn="23" />	
		<npc id="20645" count="2" respawn="23" />	
	</spawn>
	<spawn name="[aden10_2520_05]">
		<territory>	
			<location x="164120" y="80292" minz="-2464" maxz="-1864" />
			<location x="165872" y="80404" minz="-2464" maxz="-1864" />
			<location x="167452" y="84012" minz="-2464" maxz="-1864" />
			<location x="165600" y="85244" minz="-2464" maxz="-1864" />
			<location x="164092" y="83200" minz="-2464" maxz="-1864" />
		</territory>
		<npc id="20643" count="1" respawn="23" />	
		<npc id="20644" count="2" respawn="23" />	
		<npc id="20645" count="1" respawn="23" />	
	</spawn>
	<spawn name="[aden10_2520_06]">
		<territory>	
			<location x="165740" y="85248" minz="-2456" maxz="-1456" />
			<location x="167440" y="84144" minz="-2456" maxz="-1456" />
			<location x="168116" y="85428" minz="-2456" maxz="-1456" />
			<location x="168104" y="86360" minz="-2456" maxz="-1456" />
			<location x="167248" y="87112" minz="-2456" maxz="-1456" />
			<location x="165180" y="87152" minz="-2456" maxz="-1456" />
		</territory>
		<npc id="20643" count="1" respawn="23" />	
		<npc id="20644" count="2" respawn="23" />	
		<npc id="20645" count="1" respawn="23" />	
	</spawn>
	<spawn name="[aden10_2520_07]">
		<territory>	
			<location x="165084" y="87168" minz="-2472" maxz="-2072" />
			<location x="166520" y="87708" minz="-2472" maxz="-2072" />
			<location x="166500" y="88852" minz="-2472" maxz="-2072" />
			<location x="166092" y="89056" minz="-2472" maxz="-2072" />
			<location x="164792" y="88724" minz="-2472" maxz="-2072" />
		</territory>
		<npc id="20643" count="1" respawn="23" />	
		<npc id="20644" count="1" respawn="23" />	
		<npc id="20645" count="1" respawn="23" />	
	</spawn>
	<spawn name="[aden10_2520_08]">
		<territory>	
			<location x="164016" y="84076" minz="-2472" maxz="-2072" />
			<location x="165680" y="85860" minz="-2472" maxz="-2072" />
			<location x="165200" y="87056" minz="-2472" maxz="-2072" />
			<location x="163992" y="85836" minz="-2472" maxz="-2072" />
		</territory>
		<npc id="20643" count="1" respawn="23" />	
		<npc id="20644" count="1" respawn="23" />	
		<npc id="20645" count="1" respawn="23" />	
	</spawn>
	<spawn name="[aden10_2520_09]">
		<territory>	
			<location x="163968" y="86276" minz="-2800" maxz="-2350" />
			<location x="164848" y="87272" minz="-2800" maxz="-2350" />
			<location x="164444" y="88740" minz="-2800" maxz="-2350" />
			<location x="163980" y="88340" minz="-2800" maxz="-2350" />
		</territory>
		<npc id="20643" count="1" respawn="23" />	
		<npc id="20644" count="1" respawn="23" />	
		<npc id="20645" count="1" respawn="23" />	
	</spawn>
	<spawn name="[aden11_mb2520_01]">
		<territory>	
			<location x="170212" y="84744" minz="-2052" maxz="-1452" />
			<location x="171056" y="85260" minz="-2052" maxz="-1452" />
			<location x="171016" y="85976" minz="-2052" maxz="-1452" />
			<location x="170232" y="85392" minz="-2052" maxz="-1452" />
		</territory>
		<npc id="25125" count="1" respawn="129600" respawn_rand="86400" />	
	</spawn>
	<spawn name="[aden11_mb2520_02]">
		<territory>	
			<location x="164740" y="93772" minz="-3260" maxz="-2660" />
			<location x="165392" y="93248" minz="-3260" maxz="-2660" />
			<location x="166108" y="93876" minz="-3260" maxz="-2660" />
			<location x="165392" y="94488" minz="-3260" maxz="-2660" />
		</territory>
		<npc id="25089" count="1" respawn="129600" respawn_rand="86400" />	
	</spawn>
	<spawn name="[aden11_mb2520_03]">
		<territory>	
			<location x="165504" y="87576" minz="-2464" maxz="-1864" />
			<location x="166328" y="87704" minz="-2464" maxz="-1864" />
			<location x="166384" y="88744" minz="-2464" maxz="-1864" />
			<location x="165604" y="88784" minz="-2464" maxz="-1864" />
		</territory>
		<npc id="25241" count="1" respawn="129600" respawn_rand="86400" />	
	</spawn>
	<spawn name="[aden10_mb2520_04]">
		<territory>	
			<location x="165596" y="68480" minz="-3348" maxz="-2748" />
			<location x="166052" y="67440" minz="-3348" maxz="-2748" />
			<location x="166928" y="68124" minz="-3348" maxz="-2748" />
			<location x="166244" y="69028" minz="-3348" maxz="-2748" />
		</territory>
		<npc id="25463" count="1" respawn="129600" respawn_rand="86400" />	
	</spawn>
	<spawn name="[aden10_tb2520_03]" event_name="[treasure_box]">
		<territory>	
			<location x="164036" y="69844" minz="-3172" maxz="-2822" />
			<location x="166152" y="70024" minz="-3172" maxz="-2822" />
			<location x="166604" y="72564" minz="-3172" maxz="-2822" />
			<location x="165796" y="73504" minz="-3172" maxz="-2822" />
			<location x="164032" y="73700" minz="-3172" maxz="-2822" />
		</territory>
		<npc id="18276" count="2" respawn="60" />	
		<npc id="21812" count="2" respawn="60" />	
	</spawn>
	<spawn name="[aden10_tb2520_04]" event_name="[treasure_box]">
		<territory>	
			<location x="164120" y="74116" minz="-3164" maxz="-2064" />
			<location x="165344" y="73908" minz="-3164" maxz="-2064" />
			<location x="166740" y="76632" minz="-3164" maxz="-2064" />
			<location x="166404" y="80164" minz="-3164" maxz="-2064" />
			<location x="163956" y="80052" minz="-3164" maxz="-2064" />
		</territory>
		<npc id="18276" count="1" respawn="60" />	
		<npc id="21812" count="1" respawn="60" />	
	</spawn>

</list>
