=== Hl4p3x/L2JHELLAS/L2JHellasD/data/xml/spawn/spawn.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT list (spawn|location)*>
<!ELEMENT spawn (territory|npc)*>
<!ATTLIST spawn
        spawn_bydefault CDATA #REQUIRED
        name CDATA #REQUIRED
        event_name CDATA #IMPLIED>
<!ELEMENT territory (location)*>
<!ELEMENT location (#PCDATA)>
<!ATTLIST location
        maxz CDATA #REQUIRED
        minz CDATA #REQUIRED
        x CDATA #REQUIRED
        y CDATA #REQUIRED>
<!ELEMENT npc (ai_params)*>
<!ATTLIST npc
        count CDATA #REQUIRED
        id CDATA #REQUIRED
        respawn CDATA #IMPLIED
        respawn_rand CDATA #IMPLIED
        pos CDATA #IMPLIED>
<!ELEMENT ai_params (set)*>
<!ELEMENT set (#PCDATA)>
<!ATTLIST set
        name CDATA #REQUIRED
        val CDATA #REQUIRED>

=== Hl4p3x/L2JHELLAS/L2JHellasD/data/xml/spawn/16_12.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE list SYSTEM "spawn.dtd">
<list>
	<spawn name="[ssqteleport1_1612_31]">
		<npc id="31865" count="1" respawn="60" pos="-111971 -182437 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_32]">
		<npc id="31866" count="1" respawn="60" pos="-111098 -182451 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_33]">
		<npc id="31867" count="1" respawn="60" pos="-110274 -180570 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_34]">
		<npc id="31868" count="1" respawn="60" pos="-109391 -180543 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_35]">
		<npc id="31869" count="1" respawn="60" pos="-113276 -181523 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_36]">
		<npc id="31870" count="1" respawn="60" pos="-111564 -180548 -6753 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_37]">
		<npc id="31871" count="1" respawn="60" pos="-109782 -182443 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_38]">
		<npc id="31872" count="1" respawn="60" pos="-111571 -181523 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_mb1612_39]">
		<npc id="31873" count="1" respawn="60" pos="-109884 -181517 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_41]">
		<npc id="31874" count="1" respawn="60" pos="-111974 -179611 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_42]">
		<npc id="31875" count="1" respawn="60" pos="-111102 -179625 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_43]">
		<npc id="31876" count="1" respawn="60" pos="-110277 -177744 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_44]">
		<npc id="31877" count="1" respawn="60" pos="-109395 -177716 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_45]">
		<npc id="31878" count="1" respawn="60" pos="-113280 -178697 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_46]">
		<npc id="31879" count="1" respawn="60" pos="-111567 -177721 -6753 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_47]">
		<npc id="31880" count="1" respawn="60" pos="-109785 -179617 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_48]">
		<npc id="31881" count="1" respawn="60" pos="-111574 -178697 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_mb1612_49]">
		<npc id="31882" count="1" respawn="60" pos="-109888 -178691 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_51]">
	    <npc id="31883" count="1" respawn="60" pos="-113797 -175816 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_52]">
		<npc id="31884" count="1" respawn="60" pos="-114077 -174938 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_53]">
		<npc id="31885" count="1" respawn="60" pos="-115705 -174147 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_54]">
		<npc id="31886" count="1" respawn="60" pos="-115681 -173229 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_55]">
		<npc id="31887" count="1" respawn="60" pos="-114751 -177066 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_56]">
		<npc id="31888" count="1" respawn="60" pos="-115690 -175409 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_57]">
		<npc id="31889" count="1" respawn="60" pos="-113805 -173604 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_58]">
		<npc id="31890" count="1" respawn="60" pos="-114724 -175385 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_mb1612_59]">
		<npc id="31891" count="1" respawn="60" pos="-114723 -173724 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_61]">
		<npc id="31892" count="1" respawn="60" pos="-117634 -177784 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_62]">
		<npc id="31893" count="1" respawn="60" pos="-118465 -177758 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_63]">
		<npc id="31894" count="1" respawn="60" pos="-119262 -179660 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_64]">
		<npc id="31895" count="1" respawn="60" pos="-120151 -179668 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_65]">
		<npc id="31896" count="1" respawn="60" pos="-116326 -178729 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_66]">
		<npc id="31897" count="1" respawn="60" pos="-117973 -179667 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_67]">
		<npc id="31898" count="1" respawn="60" pos="-119753 -177759 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_68]">
		<npc id="31899" count="1" respawn="60" pos="-117976 -178724 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_mb1612_69]">
		<npc id="31900" count="1" respawn="60" pos="-119679 -178707 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_71]">
		<npc id="31901" count="1" respawn="60" pos="-117676 -180613 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_72]">
		<npc id="31902" count="1" respawn="60" pos="-118506 -180587 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_73]">
		<npc id="31903" count="1" respawn="60" pos="-119304 -182488 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_74]">
		<npc id="31904" count="1" respawn="60" pos="-120193 -182497 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_75]">
		<npc id="31905" count="1" respawn="60" pos="-116367 -181558 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_76]">
		<npc id="31906" count="1" respawn="60" pos="-118015 -182496 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_77]">
		<npc id="31907" count="1" respawn="60" pos="-119795 -180588 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_78]">
		<npc id="31908" count="1" respawn="60" pos="-118017 -181553 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_mb1612_79]">
		<npc id="31909" count="1" respawn="60" pos="-119720 -181536 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_81]">
		<npc id="31910" count="1" respawn="60" pos="-115720 -184407 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_82]">
		<npc id="31911" count="1" respawn="60" pos="-115714 -185264 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_83]">
		<npc id="31912" count="1" respawn="60" pos="-113830 -186056 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_84]">
		<npc id="31913" count="1" respawn="60" pos="-113828 -186929 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_85]">
		<npc id="31914" count="1" respawn="60" pos="-114797 -183022 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_86]">
		<npc id="31915" count="1" respawn="60" pos="-113868 -184724 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_87]">
		<npc id="31916" count="1" respawn="60" pos="-115704 -186503 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_1612_88]">
		<npc id="31917" count="1" respawn="60" pos="-114815 -184706 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_mb1612_89]">
		<npc id="31918" count="1" respawn="60" pos="-114803 -186399 -6755 0" />	
	</spawn>
	<spawn name="[ssqteleport1_npc1622_01]">
		<npc id="31488" count="1" respawn="60" pos="-114224 -181504 -6753 32768" />	
		<npc id="31489" count="1" respawn="60" pos="-114216 -178698 -6753 32768" />	
		<npc id="31490" count="1" respawn="60" pos="-114798 -178084 -6753 49152" />	
		<npc id="31491" count="1" respawn="60" pos="-115362 -178692 -6753 0" />	
		<npc id="31492" count="1" respawn="60" pos="-115364 -181517 -6753 0" />	
		<npc id="31493" count="1" respawn="60" pos="-114793 -182125 -6753 16384" />	
	</spawn>
</list>

=== Hl4p3x/L2JHELLAS/L2JHellasD/data/xml/spawn/20_15.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE list SYSTEM "spawn.dtd">
<list>
	<spawn name="[lyonn09_2015_12]">
		<territory>	
			<location x="11264" y="-94340" minz="-2884" maxz="-2284" />
			<location x="14592" y="-94004" minz="-2884" maxz="-2284" />
			<location x="14872" y="-92360" minz="-2884" maxz="-2284" />
			<location x="12216" y="-91088" minz="-2884" maxz="-2284" />
			<location x="11064" y="-91476" minz="-2884" maxz="-2284" />
			<location x="10752" y="-93136" minz="-2884" maxz="-2284" />
		</territory>
		<npc id="21257" count="4" respawn="15" />	
		<npc id="21117" count="5" respawn="15" />	
		<npc id="21118" count="4" respawn="15" />	
	</spawn>
	<spawn name="[lyonn09_2015_14]">
		<territory>	
			<location x="13684" y="-96912" minz="-2892" maxz="-2492" />
			<location x="15344" y="-96732" minz="-2892" maxz="-2492" />
			<location x="15388" y="-95596" minz="-2892" maxz="-2492" />
			<location x="14252" y="-94828" minz="-2892" maxz="-2492" />
			<location x="13032" y="-95872" minz="-2892" maxz="-2492" />
		</territory>
		<npc id="21257" count="4" respawn="15" />	
		<npc id="21117" count="4" respawn="15" />	
		<npc id="21118" count="4" respawn="15" />	
	</spawn>
	<spawn name="[lyonn09_2015_01]">
		<territory>	
			<location x="1716" y="-95584" minz="-3208" maxz="-2808" />
			<location x="3340" y="-95232" minz="-3208" maxz="-2808" />
			<location x="3896" y="-93496" minz="-3208" maxz="-2808" />
			<location x="3680" y="-92144" minz="-3208" maxz="-2808" />
			<location x="2248" y="-91716" minz="-3208" maxz="-2808" />
			<location x="164" y="-92840" minz="-3208" maxz="-2808" />
			<location x="188" y="-94416" minz="-3208" maxz="-2808" />
		</territory>
		<npc id="21121" count="3" respawn="15" />	
		<npc id="21122" count="3" respawn="15" />	
		<npc id="21123" count="3" respawn="15" />	
	</spawn>
	<spawn name="[lyonn09_2015_02]">
		<territory>	
			<location x="176" y="-98184" minz="-2136" maxz="-1736" />
			<location x="3456" y="-98240" minz="-2136" maxz="-1736" />
			<location x="3292" y="-97196" minz="-2136" maxz="-1736" />
			<location x="176" y="-96260" minz="-2136" maxz="-1736" />
		</territory>
		<npc id="21121" count="3" respawn="15" />	
		<npc id="21122" count="3" respawn="15" />	
		<npc id="21123" count="2" respawn="15" />	
	</spawn>
	<spawn name="[lyonn09_2015_03]">
		<territory>	
			<location x="3480" y="-98192" minz="-2064" maxz="-1664" />
			<location x="6012" y="-98212" minz="-2064" maxz="-1664" />
			<location x="5852" y="-95556" minz="-2064" maxz="-1664" />
			<location x="4512" y="-95688" minz="-2064" maxz="-1664" />
		</territory>
		<npc id="21121" count="3" respawn="15" />	
		<npc id="21122" count="2" respawn="15" />	
		<npc id="21123" count="2" respawn="15" />	
	</spawn>
	<spawn name="[lyonn09_2015_04]">
		<territory>	
			<location x="132" y="-91464" minz="-2256" maxz="-1656" />
			<location x="1584" y="-90888" minz="-2256" maxz="-1656" />
			<location x="3856" y="-89028" minz="-2256" maxz="-1656" />
			<location x="2224" y="-87424" minz="-2256" maxz="-1656" />
			<location x="112" y="-87468" minz="-2256" maxz="-1656" />
		</territory>
		<npc id="21121" count="3" respawn="15" />	
		<npc id="21122" count="3" respawn="15" />	
		<npc id="21123" count="3" respawn="15" />	
	</spawn>
	<spawn name="[lyonn09_2015_05]">
		<territory>	
			<location x="104" y="-87432" minz="-2432" maxz="-1732" />
			<location x="2132" y="-87404" minz="-2432" maxz="-1732" />
			<location x="1536" y="-84616" minz="-2432" maxz="-1732" />
			<location x="1212" y="-84224" minz="-2432" maxz="-1732" />
			<location x="128" y="-84380" minz="-2432" maxz="-1732" />
		</territory>
		<npc id="21121" count="2" respawn="15" />	
		<npc id="21122" count="2" respawn="15" />	
		<npc id="21123" count="3" respawn="15" />	
	</spawn>
	<spawn name="[lyonn09_2015_06]">
		<territory>	
			<location x="144" y="-83108" minz="-2808" maxz="-2408" />
			<location x="1752" y="-84096" minz="-2808" maxz="-2408" />
			<location x="1536" y="-82792" minz="-2808" maxz="-2408" />
			<location x="152" y="-81664" minz="-2808" maxz="-2408" />
		</territory>
		<npc id="21121" count="2" respawn="15" />	
		<npc id="21122" count="2" respawn="15" />	
		<npc id="21123" count="2" respawn="15" />	
	</spawn>
	<spawn name="[lyonn09_2015_07]">
		<territory>	
			<location x="140" y="-81596" minz="-2792" maxz="-2492" />
			<location x="1840" y="-82356" minz="-2792" maxz="-2492" />
			<location x="1448" y="-81084" minz="-2792" maxz="-2492" />
			<location x="588" y="-79828" minz="-2792" maxz="-2492" />
			<location x="124" y="-79688" minz="-2792" maxz="-2492" />
		</territory>
		<npc id="21121" count="2" respawn="15" />	
		<npc id="21122" count="2" respawn="15" />	
		<npc id="21123" count="2" respawn="15" />	
	</spawn>
	<spawn name="[lyonn09_2015_08]">
		<territory>	
			<location x="1876" y="-80128" minz="-2572" maxz="-1672" />
			<location x="2832" y="-80016" minz="-2572" maxz="-1672" />
			<location x="3868" y="-79408" minz="-2572" maxz="-1672" />
			<location x="3920" y="-77012" minz="-2572" maxz="-1672" />
			<location x="2508" y="-75780" minz="-2572" maxz="-1672" />
			<location x="140" y="-76092" minz="-2572" maxz="-1672" />
			<location x="212" y="-79092" minz="-2572" maxz="-1672" />
		</territory>
		<npc id="21121" count="4" respawn="15" />	
		<npc id="21122" count="4" respawn="15" />	
		<npc id="21123" count="4" respawn="15" />	
	</spawn>
	<spawn name="[lyonn09_2015_09]">
		<territory>	
			<location x="180" y="-75956" minz="-2104" maxz="-1704" />
			<location x="2492" y="-75668" minz="-2104" maxz="-1704" />
			<location x="2964" y="-74392" minz="-2104" maxz="-1704" />
			<location x="2280" y="-73340" minz="-2104" maxz="-1704" />
			<location x="1368" y="-73352" minz="-2104" maxz="-1704" />
			<location x="156" y="-74496" minz="-2104" maxz="-1704" />
		</territory>
		<npc id="21121" count="3" respawn="15" />	
		<npc id="21122" count="2" respawn="15" />	
		<npc id="21123" count="3" respawn="15" />	
	</spawn>
	<spawn name="[lyonn09_2015_10]">
		<territory>	
			<location x="2896" y="-84964" minz="-2736" maxz="-1936" />
			<location x="4296" y="-84972" minz="-2736" maxz="-1936" />
			<location x="4608" y="-84028" minz="-2736" maxz="-1936" />
			<location x="3560" y="-81260" minz="-2736" maxz="-1936" />
			<location x="2572" y="-81188" minz="-2736" maxz="-1936" />
		</territory>
		<npc id="21121" count="2" respawn="15" />	
		<npc id="21122" count="3" respawn="15" />	
		<npc id="21123" count="3" respawn="15" />	
	</spawn>
	<spawn name="[lyonn09_2015_11]">
		<territory>	
			<location x="15752" y="-98104" minz="-2952" maxz="-2552" />
			<location x="16304" y="-96572" minz="-2952" maxz="-2552" />
			<location x="14656" y="-94140" minz="-2952" maxz="-2552" />
			<location x="11096" y="-94424" minz="-2952" maxz="-2552" />
			<location x="12476" y="-98124" minz="-2952" maxz="-2552" />
		</territory>
		<npc id="21121" count="4" respawn="15" />	
		<npc id="21122" count="4" respawn="15" />	
		<npc id="21123" count="4" respawn="15" />	
	</spawn>
	<spawn name="[lyonn09_2015_12]">
		<territory>	
			<location x="11264" y="-94340" minz="-2884" maxz="-2284" />
			<location x="14592" y="-94004" minz="-2884" maxz="-2284" />
			<location x="14872" y="-92360" minz="-2884" maxz="-2284" />
			<location x="12216" y="-91088" minz="-2884" maxz="-2284" />
			<location x="11064" y="-91476" minz="-2884" maxz="-2284" />
			<location x="10752" y="-93136" minz="-2884" maxz="-2284" />
		</territory>
		<npc id="21121" count="4" respawn="15" />	
		<npc id="21122" count="4" respawn="15" />	
		<npc id="21123" count="3" respawn="15" />	
	</spawn>
	<spawn name="[lyonn09_2015_13]">
		<territory>	
			<location x="864" y="-94328" minz="-3296" maxz="-2696" />
			<location x="2052" y="-94724" minz="-3296" maxz="-2696" />
			<location x="3064" y="-94240" minz="-3296" maxz="-2696" />
			<location x="3268" y="-93432" minz="-3296" maxz="-2696" />
			<location x="2796" y="-92184" minz="-3296" maxz="-2696" />
			<location x="1736" y="-92060" minz="-3296" maxz="-2696" />
			<location x="988" y="-92468" minz="-3296" maxz="-2696" />
			<location x="544" y="-93292" minz="-3296" maxz="-2696" />
			<location x="508" y="-93896" minz="-3296" maxz="-2696" />
		</territory>
		<npc id="21123" count="2" respawn="15" />	
	</spawn>
	<spawn name="[lyonn09_2015_14]">
		<territory>	
			<location x="13684" y="-96912" minz="-2892" maxz="-2492" />
			<location x="15344" y="-96732" minz="-2892" maxz="-2492" />
			<location x="15388" y="-95596" minz="-2892" maxz="-2492" />
			<location x="14252" y="-94828" minz="-2892" maxz="-2492" />
			<location x="13032" y="-95872" minz="-2892" maxz="-2492" />
		</territory>
		<npc id="21123" count="2" respawn="15" />	
	</spawn>
	<spawn name="[lyonn01_qm2014_03]">
		<territory>	
			<location x="9688" y="-92960" minz="-3100" maxz="-2400" />
			<location x="10460" y="-93268" minz="-3100" maxz="-2400" />
			<location x="11136" y="-90396" minz="-3100" maxz="-2400" />
			<location x="9608" y="-88708" minz="-3100" maxz="-2400" />
			<location x="9044" y="-89312" minz="-3100" maxz="-2400" />
		</territory>
		<npc id="20778" count="4" respawn="180" />	
		<npc id="20779" count="4" respawn="180" />	
	</spawn>
	<spawn name="[lyonn01_npc2015_g01]">
		<npc id="31036" count="1" respawn="60" pos="2688 -93280 -3148 0" />	
	</spawn>
	<spawn name="[lyonn01_npc2015_g02]">
		<npc id="31036" count="1" respawn="60" pos="2384 -84912 -2640 0" />	
	</spawn>
	<spawn name="[lyonn01_npc2015_g03]">
		<npc id="31036" count="1" respawn="60" pos="13680 -94528 -2832 0" />	
	</spawn>

</list>

=== Hl4p3x/L2JHELLAS/L2JHellasD/data/xml/spawn/16_24.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE list SYSTEM "spawn.dtd">
<list>
	<spawn name="[gludio31_1624_01]">
		<territory>	
			<location x="-106442" y="222221" minz="-3789" maxz="-3189" />
			<location x="-100607" y="225882" minz="-3789" maxz="-3189" />
			<location x="-101548" y="229015" minz="-3789" maxz="-3189" />
			<location x="-108902" y="228236" minz="-3789" maxz="-3189" />
		</territory>
		<npc id="20098" count="8" respawn="20" />	
		<npc id="20342" count="8" respawn="20" />	
		<npc id="20016" count="4" respawn="20" />	
	</spawn>
	<spawn name="[gludio31_1624_02]">
		<territory>	
			<location x="-100997" y="220951" minz="-3730" maxz="-3030" />
			<location x="-100118" y="224043" minz="-3730" maxz="-3030" />
			<location x="-100529" y="225783" minz="-3730" maxz="-3030" />
			<location x="-105570" y="222170" minz="-3730" maxz="-3030" />
		</territory>
		<npc id="20342" count="9" respawn="20" />	
		<npc id="20016" count="2" respawn="20" />	
	</spawn>
	<spawn name="[gludio31_1624_03]">
		<territory>	
			<location x="-100147" y="212767" minz="-3435" maxz="-2835" />
			<location x="-99236" y="214857" minz="-3435" maxz="-2835" />
			<location x="-100642" y="217336" minz="-3435" maxz="-2835" />
			<location x="-104630" y="213491" minz="-3435" maxz="-2835" />
			<location x="-101820" y="212285" minz="-3435" maxz="-2835" />
		</territory>
		<npc id="20016" count="7" respawn="20" />	
		<npc id="20101" count="5" respawn="20" />	
	</spawn>
	<spawn name="[gludio31_1624_04]">
		<territory>	
			<location x="-104578" y="215090" minz="-3482" maxz="-2782" />
			<location x="-101716" y="217877" minz="-3482" maxz="-2782" />
			<location x="-104925" y="218078" minz="-3482" maxz="-2782" />
			<location x="-106813" y="215321" minz="-3482" maxz="-2782" />
		</territory>
		<npc id="20016" count="4" respawn="20" />	
		<npc id="20101" count="3" respawn="20" />	
	</spawn>
	<spawn name="[gludio31_1624_05]">
		<territory>	
			<location x="-106991" y="215229" minz="-3442" maxz="-2742" />
			<location x="-105618" y="217251" minz="-3442" maxz="-2742" />
			<location x="-109305" y="217518" minz="-3442" maxz="-2742" />
			<location x="-110197" y="216637" minz="-3442" maxz="-2742" />
			<location x="-109339" y="215079" minz="-3442" maxz="-2742" />
		</territory>
		<npc id="20101" count="4" respawn="20" />	
		<npc id="20103" count="3" respawn="20" />	
	</spawn>
	<spawn name="[gludio31_1624_06]">
		<territory>	
			<location x="-111461" y="215904" minz="-3299" maxz="-2599" />
			<location x="-109306" y="217637" minz="-3299" maxz="-2599" />
			<location x="-112836" y="219633" minz="-3299" maxz="-2599" />
			<location x="-114182" y="217830" minz="-3299" maxz="-2599" />
		</territory>
		<npc id="20101" count="4" respawn="20" />	
		<npc id="20103" count="4" respawn="20" />	
	</spawn>
	<spawn name="[gludio31_1624_07]">
		<territory>	
			<location x="-114359" y="217913" minz="-3242" maxz="-2542" />
			<location x="-112863" y="219836" minz="-3242" maxz="-2542" />
			<location x="-114072" y="221617" minz="-3242" maxz="-2542" />
			<location x="-116931" y="221387" minz="-3242" maxz="-2542" />
		</territory>
		<npc id="20101" count="3" respawn="20" />	
		<npc id="20103" count="3" respawn="20" />	
	</spawn>
	<spawn name="[gludio31_1624_08]">
		<territory>	
			<location x="-117051" y="221485" minz="-3242" maxz="-2542" />
			<location x="-115028" y="224544" minz="-3242" maxz="-2542" />
			<location x="-115611" y="225856" minz="-3242" maxz="-2542" />
			<location x="-118537" y="225708" minz="-3242" maxz="-2542" />
		</territory>
		<npc id="20103" count="4" respawn="20" />	
		<npc id="20106" count="3" respawn="20" />	
	</spawn>
	<spawn name="[gludio31_1624_09]">
		<territory>	
			<location x="-118599" y="225847" minz="-3036" maxz="-2336" />
			<location x="-115531" y="225992" minz="-3036" maxz="-2336" />
			<location x="-116377" y="229099" minz="-3036" maxz="-2336" />
			<location x="-119616" y="229082" minz="-3036" maxz="-2336" />
		</territory>
		<npc id="20101" count="2" respawn="20" />	
		<npc id="20103" count="3" respawn="20" />	
		<npc id="20106" count="3" respawn="20" />	
	</spawn>
	<spawn name="[gludio31_1624_10s]">
		<territory>	
			<location x="-105979" y="223357" minz="-3783" maxz="-3283" />
			<location x="-103968" y="223997" minz="-3783" maxz="-3283" />
			<location x="-104347" y="225843" minz="-3783" maxz="-3283" />
			<location x="-106603" y="225203" minz="-3783" maxz="-3283" />
		</territory>
		<npc id="20101" count="3" respawn="20" />	
		<npc id="20103" count="1" respawn="20" />	
	</spawn>
	<spawn name="[gludio31_1624_11s]">
		<territory>	
			<location x="-104681" y="226275" minz="-3814" maxz="-3314" />
			<location x="-102189" y="226251" minz="-3814" maxz="-3314" />
			<location x="-102039" y="228239" minz="-3814" maxz="-3314" />
			<location x="-105068" y="227850" minz="-3814" maxz="-3314" />
		</territory>
		<npc id="20016" count="2" respawn="20" />	
		<npc id="20101" count="2" respawn="20" />	
	</spawn>
	<spawn name="[gludio32_npc1624_001]">
		<npc id="30405" count="1" respawn="60" pos="-115080 222168 -2930 42000" />	
	</spawn>
	<spawn name="[gludio32_npc1624_002]">
		<npc id="30407" count="1" respawn="60" pos="-104240 222064 -3437 16384" />	
	</spawn>
	<spawn name="[gludio32_npc1624_003]">
		<npc id="30497" count="1" respawn="60" pos="-114685 222291 -2925 44000" />	
	</spawn>
	<spawn name="[gludio31_npc1624_g01]">
		<npc id="31032" count="1" respawn="60" pos="-101408 223680 -3488 0" />	
		<npc id="31032" count="1" respawn="60" pos="-104000 224544 -3616 0" />	
		<npc id="31032" count="1" respawn="60" pos="-105712 227392 -3616 0" />	
		<npc id="31032" count="1" respawn="60" pos="-102320 227600 -3664 0" />	
	</spawn>
	<spawn name="[gludio31_npc1624_g02]">
		<npc id="31032" count="1" respawn="60" pos="-101904 214640 -3216 0" />	
		<npc id="31032" count="1" respawn="60" pos="-104864 215952 -3292 0" />	
		<npc id="31032" count="1" respawn="60" pos="-102256 219104 -3040 0" />	
	</spawn>
	<spawn name="[gludio31_npc1624_g03]">
		<npc id="31032" count="1" respawn="60" pos="-117248 226784 -2912 0" />	
		<npc id="31032" count="1" respawn="60" pos="-115168 220864 -3024 0" />	
	</spawn>

</list>

=== Hl4p3x/L2JHELLAS/L2JHellasD/data/xml/spawn/16_21.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE list SYSTEM "spawn.dtd">
<list>
	<spawn spawn_bydefault="true"  name="[gludio15_1621_01]">
		<territory>	
			<location x="-99708" y="100418" minz="-3692" maxz="-2992" />
			<location x="-98553" y="100158" minz="-3692" maxz="-2992" />
			<location x="-98637" y="104050" minz="-3692" maxz="-2992" />
			<location x="-101237" y="103989" minz="-3692" maxz="-2992" />
		</territory>
		<npc id="20498" count="2" respawn="60" respawn_rand="20" />	
		<npc id="20497" count="2" respawn="60" respawn_rand="20" />	
		<npc id="20501" count="1" respawn="60" respawn_rand="20" />	
		<npc id="20495" count="1" respawn="60" respawn_rand="20" />	
	</spawn>
	<spawn spawn_bydefault="true"  name="[gludio15_1621_02]">
		<territory>	
			<location x="-100403" y="104743" minz="-3715" maxz="-3015" />
			<location x="-98598" y="104208" minz="-3715" maxz="-3015" />
			<location x="-98544" y="109423" minz="-3715" maxz="-3015" />
			<location x="-100571" y="106885" minz="-3715" maxz="-3015" />
		</territory>
		<npc id="20498" count="2" respawn="60" respawn_rand="20" />	
		<npc id="20497" count="2" respawn="60" respawn_rand="20" />	
		<npc id="20501" count="2" respawn="60" respawn_rand="20" />	
	</spawn>

</list>

=== Hl4p3x/L2JHELLAS/L2JHellasD/data/xml/spawn/17_23.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE list SYSTEM "spawn.dtd">
<list>
	<spawn name="[gludio34_1723_01]">
		<territory>	
			<location x="-78051" y="164047" minz="-3764" maxz="-3064" />
			<location x="-72417" y="163960" minz="-3764" maxz="-3064" />
			<location x="-69351" y="168540" minz="-3764" maxz="-3064" />
			<location x="-75103" y="169497" minz="-3764" maxz="-3064" />
		</territory>
		<npc id="20030" count="6" respawn="21" />	
		<npc id="20017" count="7" respawn="21" />	
		<npc id="20038" count="5" respawn="21" />	
	</spawn>
	<spawn name="[gludio34_1723_02]">
		<territory>	
			<location x="-72204" y="163988" minz="-3879" maxz="-2979" />
			<location x="-65828" y="164053" minz="-3879" maxz="-2979" />
			<location x="-65850" y="168094" minz="-3879" maxz="-2979" />
			<location x="-69278" y="168439" minz="-3879" maxz="-2979" />
		</territory>
		<npc id="20017" count="6" respawn="21" />	
		<npc id="20038" count="4" respawn="21" />	
	</spawn>
	<spawn name="[gludio34_1723_03]">
		<territory>	
			<location x="-74404" y="169620" minz="-3764" maxz="-3064" />
			<location x="-65854" y="168232" minz="-3764" maxz="-3064" />
			<location x="-65833" y="172134" minz="-3764" maxz="-3064" />
			<location x="-70810" y="174081" minz="-3764" maxz="-3064" />
		</territory>
		<npc id="20017" count="8" respawn="21" />	
		<npc id="20038" count="5" respawn="21" />	
		<npc id="20043" count="5" respawn="21" />	
	</spawn>
	<spawn name="[gludio34_1723_04]">
		<territory>	
			<location x="-70751" y="174144" minz="-3764" maxz="-3064" />
			<location x="-65817" y="172251" minz="-3764" maxz="-3064" />
			<location x="-65849" y="178207" minz="-3764" maxz="-3064" />
			<location x="-67684" y="178315" minz="-3764" maxz="-3064" />
		</territory>
		<npc id="20043" count="5" respawn="21" />	
		<npc id="20050" count="3" respawn="21" />	
	</spawn>
	<spawn name="[gludio34_1723_05s]">
		<territory>	
			<location x="-68365" y="174048" minz="-3764" maxz="-3064" />
			<location x="-66111" y="172916" minz="-3764" maxz="-3064" />
			<location x="-66030" y="175473" minz="-3764" maxz="-3064" />
			<location x="-67795" y="176370" minz="-3764" maxz="-3064" />
		</territory>
		<npc id="20030" count="2" respawn="21" />	
		<npc id="20017" count="2" respawn="21" />	
	</spawn>
	<spawn name="[gludio34_1723_06s]">
		<territory>	
			<location x="-70521" y="170043" minz="-3764" maxz="-3064" />
			<location x="-67872" y="168756" minz="-3764" maxz="-3064" />
			<location x="-67115" y="171426" minz="-3764" maxz="-3064" />
			<location x="-69289" y="171970" minz="-3764" maxz="-3064" />
		</territory>
		<npc id="20030" count="2" respawn="21" />	
		<npc id="20017" count="2" respawn="21" />	
	</spawn>
	<spawn name="[gludio34_1723_07s]">
		<territory>	
			<location x="-70675" y="164924" minz="-3764" maxz="-3064" />
			<location x="-68364" y="164342" minz="-3764" maxz="-3064" />
			<location x="-67508" y="166448" minz="-3764" maxz="-3064" />
			<location x="-69174" y="167754" minz="-3764" maxz="-3064" />
		</territory>
		<npc id="20017" count="2" respawn="21" />	
		<npc id="20038" count="2" respawn="21" />	
	</spawn>
	<spawn name="[gludio34_1723_08s]">
		<territory>	
			<location x="-74778" y="166929" minz="-3764" maxz="-3064" />
			<location x="-72707" y="165515" minz="-3764" maxz="-3064" />
			<location x="-70878" y="167465" minz="-3764" maxz="-3064" />
			<location x="-73235" y="168518" minz="-3764" maxz="-3064" />
		</territory>
		<npc id="20017" count="2" respawn="21" />	
		<npc id="20043" count="2" respawn="21" />	
	</spawn>

</list>
