=== Hl4p3x/L2JHELLAS/L2JHellasD/data/templates/armors.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence maxOccurs="1" minOccurs="1">
				<xs:element name="item" maxOccurs="100" minOccurs="1">
					<xs:complexType>
						<xs:sequence maxOccurs="1" minOccurs="1">
							<xs:element name="for" maxOccurs="1" minOccurs="0">
								<xs:complexType>
									<xs:choice maxOccurs="unbounded" minOccurs="1">
										<xs:element name="add" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence minOccurs="0" maxOccurs="1">
													<xs:element name="and" maxOccurs="unbounded" minOccurs="1">
														<xs:complexType>
															<xs:sequence minOccurs="1" maxOccurs="1">
																<xs:element name="using" maxOccurs="unbounded" minOccurs="1">
																	<xs:complexType>
																		<xs:attribute name="slotitem" type="xs:token"  use="required"/>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="order" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:token" />
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="stat" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:token">
															<xs:enumeration value="CON" />
															<xs:enumeration value="DEX" />
															<xs:enumeration value="STR" />
															<xs:enumeration value="WIT" />
															<xs:enumeration value="MEN" />
															<xs:enumeration value="INT" />
															<xs:enumeration value="maxLoad" />
															<xs:enumeration value="pAtkSpd" />
															<xs:enumeration value="mAtkSpd" />
															<xs:enumeration value="sleepVuln" />
															<xs:enumeration value="rootVuln" />
															<xs:enumeration value="stunVuln" />
															<xs:enumeration value="bleedVuln" />
															<xs:enumeration value="rCrit" />
															<xs:enumeration value="magicSuccRes" />
															<xs:enumeration value="reflectDam" />
															<xs:enumeration value="runSpd" />
															<xs:enumeration value="accCombat" />
															<xs:enumeration value="darkRes" />
															<xs:enumeration value="earthRes" />
															<xs:enumeration value="fireRes" />
															<xs:enumeration value="holyPower" />
															<xs:enumeration value="holyRes" />
															<xs:enumeration value="mAtk" />
															<xs:enumeration value="maxMp" />
															<xs:enumeration value="maxHp" />
															<xs:enumeration value="mDef" />
															<xs:enumeration value="pAtk" />
															<xs:enumeration value="pDef" />
															<xs:enumeration value="waterRes" />
															<xs:enumeration value="windRes" />
															<xs:enumeration value="mCritRate" />
															<xs:enumeration value="rEvas" />
															<xs:enumeration value="cAtk" />
															<xs:enumeration value="maxCp" />
															<xs:enumeration value="waterVuln" />
															<xs:enumeration value="fireVuln" />
															<xs:enumeration value="windVuln" />
															<xs:enumeration value="earthVuln" />
															<xs:enumeration value="darkVuln" />
															<xs:enumeration value="cancel" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="val" type="xs:decimal" use="required" />
											</xs:complexType>
										</xs:element>
										<xs:element name="enchant" maxOccurs="2" minOccurs="0">
											<xs:complexType>
												<xs:attribute name="order" type="xs:token" use="required" />
												<xs:attribute name="stat" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:token">
															<xs:enumeration value="CON" />
															<xs:enumeration value="DEX" />
															<xs:enumeration value="STR" />
															<xs:enumeration value="WIT" />
															<xs:enumeration value="MEN" />
															<xs:enumeration value="INT" />
															<xs:enumeration value="maxLoad" />
															<xs:enumeration value="pAtkSpd" />
															<xs:enumeration value="mAtkSpd" />
															<xs:enumeration value="sleepVuln" />
															<xs:enumeration value="rootVuln" />
															<xs:enumeration value="stunVuln" />
															<xs:enumeration value="bleedVuln" />
															<xs:enumeration value="rCrit" />
															<xs:enumeration value="magicSuccRes" />
															<xs:enumeration value="reflectDam" />
															<xs:enumeration value="runSpd" />
															<xs:enumeration value="accCombat" />
															<xs:enumeration value="darkRes" />
															<xs:enumeration value="earthRes" />
															<xs:enumeration value="fireRes" />
															<xs:enumeration value="holyPower" />
															<xs:enumeration value="holyRes" />
															<xs:enumeration value="mAtk" />
															<xs:enumeration value="maxMp" />
															<xs:enumeration value="maxHp" />
															<xs:enumeration value="mDef" />
															<xs:enumeration value="pAtk" />
															<xs:enumeration value="pDef" />
															<xs:enumeration value="waterRes" />
															<xs:enumeration value="windRes" />
															<xs:enumeration value="mCritRate" />
															<xs:enumeration value="rEvas" />
															<xs:enumeration value="cAtk" />
															<xs:enumeration value="maxCp" />
															<xs:enumeration value="waterVuln" />
															<xs:enumeration value="fireVuln" />
															<xs:enumeration value="windVuln" />
															<xs:enumeration value="earthVuln" />
															<xs:enumeration value="darkVuln" />
															<xs:enumeration value="cancel" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="val" type="xs:integer" use="required" />
											</xs:complexType>
										</xs:element>
										<xs:element name="mul" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence minOccurs="0" maxOccurs="1">
													<xs:element name="and" maxOccurs="unbounded" minOccurs="1">
														<xs:complexType>
															<xs:sequence minOccurs="1" maxOccurs="1">
																<xs:element name="using" maxOccurs="unbounded" minOccurs="1">
																	<xs:complexType>
																		<xs:attribute name="slotitem" type="xs:token"  use="required"/>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="order">
													<xs:simpleType>
														<xs:restriction base="xs:token" />
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="stat">
													<xs:simpleType>
														<xs:restriction base="xs:token">
															<xs:enumeration value="CON" />
															<xs:enumeration value="DEX" />
															<xs:enumeration value="STR" />
															<xs:enumeration value="WIT" />
															<xs:enumeration value="MEN" />
															<xs:enumeration value="INT" />
															<xs:enumeration value="maxLoad" />
															<xs:enumeration value="pAtkSpd" />
															<xs:enumeration value="mAtkSpd" />
															<xs:enumeration value="sleepVuln" />
															<xs:enumeration value="rootVuln" />
															<xs:enumeration value="stunVuln" />
															<xs:enumeration value="bleedVuln" />
															<xs:enumeration value="rCrit" />
															<xs:enumeration value="magicSuccRes" />
															<xs:enumeration value="reflectDam" />
															<xs:enumeration value="runSpd" />
															<xs:enumeration value="accCombat" />
															<xs:enumeration value="darkRes" />
															<xs:enumeration value="earthRes" />
															<xs:enumeration value="fireRes" />
															<xs:enumeration value="holyPower" />
															<xs:enumeration value="holyRes" />
															<xs:enumeration value="mAtk" />
															<xs:enumeration value="maxMp" />
															<xs:enumeration value="maxHp" />
															<xs:enumeration value="mDef" />
															<xs:enumeration value="pAtk" />
															<xs:enumeration value="pDef" />
															<xs:enumeration value="waterRes" />
															<xs:enumeration value="windRes" />
															<xs:enumeration value="mCritRate" />
															<xs:enumeration value="rEvas" />
															<xs:enumeration value="cAtk" />
															<xs:enumeration value="maxCp" />
															<xs:enumeration value="waterVuln" />
															<xs:enumeration value="fireVuln" />
															<xs:enumeration value="windVuln" />
															<xs:enumeration value="earthVuln" />
															<xs:enumeration value="darkVuln" />
															<xs:enumeration value="cancel" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="val" type="xs:decimal" />
											</xs:complexType>
										</xs:element>
										<xs:element name="set" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence minOccurs="0" maxOccurs="1">
													<xs:element name="and" maxOccurs="unbounded" minOccurs="1">
														<xs:complexType>
															<xs:sequence minOccurs="1" maxOccurs="1">
																<xs:element name="using" maxOccurs="unbounded" minOccurs="1">
																	<xs:complexType>
																		<xs:attribute name="slotitem" type="xs:token"  use="required"/>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="order" type="xs:token" />
												<xs:attribute name="stat" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:token">
															<xs:enumeration value="CON" />
															<xs:enumeration value="DEX" />
															<xs:enumeration value="STR" />
															<xs:enumeration value="WIT" />
															<xs:enumeration value="MEN" />
															<xs:enumeration value="INT" />
															<xs:enumeration value="maxLoad" />
															<xs:enumeration value="pAtkSpd" />
															<xs:enumeration value="mAtkSpd" />
															<xs:enumeration value="sleepVuln" />
															<xs:enumeration value="rootVuln" />
															<xs:enumeration value="stunVuln" />
															<xs:enumeration value="bleedVuln" />
															<xs:enumeration value="rCrit" />
															<xs:enumeration value="magicSuccRes" />
															<xs:enumeration value="reflectDam" />
															<xs:enumeration value="runSpd" />
															<xs:enumeration value="accCombat" />
															<xs:enumeration value="darkRes" />
															<xs:enumeration value="earthRes" />
															<xs:enumeration value="fireRes" />
															<xs:enumeration value="holyPower" />
															<xs:enumeration value="holyRes" />
															<xs:enumeration value="mAtk" />
															<xs:enumeration value="maxMp" />
															<xs:enumeration value="maxHp" />
															<xs:enumeration value="mDef" />
															<xs:enumeration value="pAtk" />
															<xs:enumeration value="pDef" />
															<xs:enumeration value="waterRes" />
															<xs:enumeration value="windRes" />
															<xs:enumeration value="mCritRate" />
															<xs:enumeration value="rEvas" />
															<xs:enumeration value="cAtk" />
															<xs:enumeration value="maxCp" />
															<xs:enumeration value="waterVuln" />
															<xs:enumeration value="fireVuln" />
															<xs:enumeration value="windVuln" />
															<xs:enumeration value="earthVuln" />
															<xs:enumeration value="darkVuln" />
															<xs:enumeration value="cancel" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="val" type="xs:integer" use="required" />
											</xs:complexType>
										</xs:element>
										<xs:element name="sub" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence minOccurs="0" maxOccurs="1">
													<xs:element name="and" maxOccurs="unbounded" minOccurs="1">
														<xs:complexType>
															<xs:sequence minOccurs="1" maxOccurs="1">
																<xs:element name="using" maxOccurs="unbounded" minOccurs="1">
																	<xs:complexType>
																		<xs:attribute name="slotitem" type="xs:token" use="required"/>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="order" type="xs:token" use="required" />
												<xs:attribute name="stat" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:token">
															<xs:enumeration value="CON" />
															<xs:enumeration value="DEX" />
															<xs:enumeration value="STR" />
															<xs:enumeration value="WIT" />
															<xs:enumeration value="MEN" />
															<xs:enumeration value="INT" />
															<xs:enumeration value="maxLoad" />
															<xs:enumeration value="pAtkSpd" />
															<xs:enumeration value="mAtkSpd" />
															<xs:enumeration value="sleepVuln" />
															<xs:enumeration value="rootVuln" />
															<xs:enumeration value="stunVuln" />
															<xs:enumeration value="bleedVuln" />
															<xs:enumeration value="rCrit" />
															<xs:enumeration value="magicSuccRes" />
															<xs:enumeration value="reflectDam" />
															<xs:enumeration value="runSpd" />
															<xs:enumeration value="accCombat" />
															<xs:enumeration value="darkRes" />
															<xs:enumeration value="earthRes" />
															<xs:enumeration value="fireRes" />
															<xs:enumeration value="holyPower" />
															<xs:enumeration value="holyRes" />
															<xs:enumeration value="mAtk" />
															<xs:enumeration value="maxMp" />
															<xs:enumeration value="maxHp" />
															<xs:enumeration value="mDef" />
															<xs:enumeration value="pAtk" />
															<xs:enumeration value="pDef" />
															<xs:enumeration value="waterRes" />
															<xs:enumeration value="windRes" />
															<xs:enumeration value="mCritRate" />
															<xs:enumeration value="rEvas" />
															<xs:enumeration value="cAtk" />
															<xs:enumeration value="maxCp" />
															<xs:enumeration value="waterVuln" />
															<xs:enumeration value="fireVuln" />
															<xs:enumeration value="windVuln" />
															<xs:enumeration value="earthVuln" />
															<xs:enumeration value="darkVuln" />
															<xs:enumeration value="cancel" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="val" type="xs:integer" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:choice>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:positiveInteger">
									<xs:minInclusive value="1" />
									<xs:maxInclusive value="65535" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="name" type="xs:normalizedString" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Hl4p3x/L2JHELLAS/L2JHellasD/data/stats/armor/8600-8699.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../templates/armors.xsd">
	<item id="8660" name="Demon Horns">
		<for>
			<add val="0" order="0x10" stat="pDef" />
		</for>
	</item>
	<item id="8661" name="Mask of Spirits">
		<for>
			<add val="0" order="0x10" stat="pDef" />
		</for>
	</item>
	<item id="8662" name="Fairy Antennae - For Event">
		<for>
			<add val="0" order="0x10" stat="pDef" />
		</for>
	</item>
</list>

=== Hl4p3x/L2JHELLAS/L2JHellasD/data/stats/armor/9200-9299.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../templates/armors.xsd">
	<item id="9200" name="Jester Hat - Firework">
		<for>
			<add val="0" order="0x10" stat="pDef" />
		</for>
	</item>
	<item id="9201" name="Wizard\'s Hat - Firework">
		<for>
			<add val="0" order="0x10" stat="pDef" />
		</for>
	</item>
	<item id="9202" name="Dapper Hat - Firework">
		<for>
			<add val="0" order="0x10" stat="pDef" />
		</for>
	</item>
	<item id="9203" name="Romantic Chapeau - Firework">
		<for>
			<add val="0" order="0x10" stat="pDef" />
		</for>
	</item>
	<item id="9204" name="Iron Circlet - Firework">
		<for>
			<add val="0" order="0x10" stat="pDef" />
		</for>
	</item>
	<item id="9208" name="Phantom Mask - For Events Only">
		<for>
			<add val="0" order="0x10" stat="pDef" />
		</for>
	</item>
</list>
